version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "22:00"
  open-pull-requests-limit: 10
  reviewers:
  - sony-mathew
  - sojan-official
  - subintp
  labels:
  - dependencies
  - ruby
  ignore:
  - dependency-name: twilio-ruby
    versions:
    - 5.46.0
    - 5.46.1
    - 5.47.0
    - 5.48.0
    - 5.49.0
    - 5.50.0
    - 5.51.0
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
    - 1.88.0
    - 1.88.1
    - 1.90.0
    - 1.91.0
    - 1.92.0
    - 1.93.0
  - dependency-name: bootsnap
    versions:
    - 1.5.1
    - 1.7.0
    - 1.7.2
    - 1.7.3
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: jbuilder
    versions:
    - 2.11.1
  - dependency-name: groupdate
    versions:
    - 5.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "22:00"
  open-pull-requests-limit: 10
  reviewers:
  - pranavrajs
  - nithindavid
  labels:
  - dependencies
  - javascript
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: ionicons
    versions:
    - 5.3.0
    - 5.4.0
    - 5.5.0
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: expect-more-jest
    versions:
    - 5.2.1
